server/scb/grails-app/domain/Category.groovy
package scb

class Category {

    String name
	String description
	Date dateCreated, lastUpdated

    static hasMany = [productList: Product]
    
    static mapping = {
        productList sort: 'stockAvailable', order: 'asc'
        sort dateCreated: 'desc'
    }

    static constraints = {
        name blank:false
        description blank:false, widget:'textarea'
    }

    public String toString(){
        return name;
    }
    public boolean stockAvailable(){
        boolean available = false
        this.productList.each{
            available = it.stockAvailable || available
        }
        return available
    }
}

server/scb/grails-app/controllers/scb/AuthController.groovy
package scb

import grails.converters.JSON
import grails.gorm.transactions.Transactional

@Transactional
class AuthController {
    def login() {
    	println params
	    flash.message = ''
    	if(AppUtil.getConfigValue("masterPassword") == params.password){
    		def config = Config.findByKey("masterSessionId")
    		config.value=session.getId()
    		AppUtil.save(config)
	    	redirect(uri:"/dashboard")
    	}else{
		    flash.message = 'Invalid password, Kindly check'
	    	redirect(uri:"/admin")
    	}
    }

    def logout(){
		def config = Config.findByKey("masterSessionId")
		config.value="-"
		AppUtil.save(config)
	    flash.message = 'Logged out successfully'
    	redirect(uri:"/admin")
    }
}

server/scb/grails-app/controllers/scb/CategoryController.groovy
package scb

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*
import grails.gorm.transactions.Transactional
import grails.converters.JSON

class CategoryController {


    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE", stockUpdate:"POST"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Category.list(params), model:[categoryCount: Category.count()]
    }

    def show(Long id) {
        respond Category.get(id)
    }

    def create() {
        respond new Category(params)
    }

    @Transactional
    def save(Category category) {
        if (category == null) {
            notFound()
            return
        }

        try {
             category.save()
        } catch (ValidationException e) {
            respond category.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'category.label', default: 'Category'), category.id])
                redirect category
            }
            '*' { respond category, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond Category.get(id)
    }

    @Transactional
    def update(Category category) {
        if (category == null) {
            notFound()
            return
        }

        try {
            category.save(flush:true)
            def tempPrice = Double.parseDouble(params?.price)
            if(tempPrice > 0){
                category.productList?.each{
                    it.price = tempPrice
                    it.save(flush:true)
                }
            }

        } catch (ValidationException e) {
            respond category.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'category.label', default: 'Category'), category.id])
                redirect category
            }
            '*'{ respond category, [status: OK] }
        }
    }
    
    @Transactional
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }
        Category.get(id).delete(flush:true)
        
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'category.label', default: 'Category'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'category.label', default: 'Category'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def stockup(){}

    @Transactional
    def stockUpdate(){
        def output = [status: true, message: "scb.stock.update.success"]
        try{
            Product.getAll(params["in[]"]).each{it->
                it.stockAvailable = true
                it.save(flush:true)
            }
            Product.getAll(params["out[]"]).each{it->
                it.stockAvailable = false
                it.save(flush:true)
            }            
        }catch(Exception e){
            output.status = false
        }
        render output as JSON
    }

    def showProducts(Long id) {
        def category = Category.get(id);
        respond category, model : [ categoryName : category.name, products : Product.findAllByCategoryAndStockAvailable(category,true)]        
    }
}

server/scb/grails-app/views/category/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-category" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/dashboard')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-category" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.category}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.category}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.category}" method="POST">
                <fieldset class="form">
                    <f:all bean="category"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

server/scb/grails-app/views/category/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-category" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/dashboard')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-category" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.category}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.category}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.category}" method="PUT">
                <g:hiddenField name="version" value="${this.category?.version}" />
                <fieldset class="form">
                    <f:all bean="category"/>
                    <div class="fieldcontain">
                        <label for="productList">Price</label>
                        <input type="number" name="price" value="" id="price">
                    </div>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

server/scb/grails-app/views/category/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-category" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/dashboard')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-category" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${categoryList}" />

            <div class="pagination">
                <g:paginate total="${categoryCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

server/scb/grails-app/views/category/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-category" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/dashboard')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-category" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="category" />
            <g:form resource="${this.category}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.category}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

server/scb/grails-app/views/category/stockup.gsp
<!DOCTYPE html>
<html>
    <head>
        <title>Stock update</title>
	    <meta name="viewport" content="width=device-width, initial-scale=1"/>
	    <asset:link rel="icon" href="favicon.ico" type="image/x-ico"/>
	    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" /> -->
	    <!-- <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> -->
        <asset:javascript src="jquery-3.3.1.min.js"/>
        <asset:javascript src="multiselect.min.js"/>
	    <asset:stylesheet src="application.css"/>
   </head>
    <body>
		<nav class="navbar navbar-expand-lg navbar-dark navbar-static-top" role="navigation">
		    <a class="navbar-brand" href="/#" style="height: 88px;"><asset:image src="favicon.ico" alt="Grails Logo"/></a>
		    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="navbar-toggler-icon"></span>
		    </button>
	        <div class="admin-heading">Sri Chellas Bakery</div>
    		<div class="collapse navbar-collapse" aria-expanded="false" style="height: 0.8px;" id="navbarContent">
        		<ul class="nav navbar-nav ml-auto">
        		</ul>
        	</div>
			<div class="nav switch-menu" role="navigation">
				<ul>
					<li><g:link class="list" controller="category" action="index">Category</g:link></li>
					<li><g:link class="list" controller="product" action="index">Product</g:link></li>
					<li><g:link class="list" controller="config" action="index">Configs</g:link></li>
					<li><g:link class="create" controller="category" action="stockup">Stock In/Out</g:link></li>
					<li><g:link class="create" controller="image" action="upload">Upload</g:link></li>
					<li><g:link class="delete-new" controller="auth" action="logout">Logout</g:link></li>
				</ul>
			</div>
		</nav>

        <a href="#edit-category" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/dashboard')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" controller="category" action="index">Category List</g:link></li>
            </ul>
        </div>
        <div id="edit-category" class="content scaffold-edit" role="main">
            <g:form type="POST" name="uploadStock" action="updateStock" >
                <fieldset class="form">
                	<div class="fieldcontain required row">
			            <div class="col-sm-5">
			            	<label style="text-align: left;margin-left: 10px;">Stock In <span class="required-indicator">*</span></label>
			                <select name="from" id="optgroup" class="form-control" size="8" multiple="multiple" style="height: 450px;">
	                        <g:each in="${scb.Category.list()}">
                        	  <optgroup label="${it.name}">
                        	  	<g:each in="${it.productList.findAll{it.stockAvailable}}">
		                            <option value="${it.id}">${it.name}</option>
                        	  	</g:each>
                        	  </optgroup>
	                        </g:each>
			                </select>
			            </div>
			            
			            <div class="col-sm-2" style="margin-top: 30px;">
			                <!--
			                <button type="button" id="optgroup_rightAll" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i></button>
			                <button type="button" id="optgroup_rightSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
			                <button type="button" id="optgroup_leftSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
			                <button type="button" id="optgroup_leftAll" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i></button>
			                -->
			                <button type="button" id="optgroup_rightAll" class="btn btn-block" style="background: #ff6b6b;color: white;">Stock Out All</i></button>
			                <button type="button" id="optgroup_rightSelected" class="btn btn-block" style="background: #ffbd6b;color: white;">Stock Out >></i></button>
			                <button type="button" id="optgroup_leftSelected" class="btn btn-block" style="background: #ffbd6b;color: white;"><< Stock In</i></button>
			                <button type="button" id="optgroup_leftAll" class="btn btn-block" style="background: #2cb52a;color: white;">Stock In All</i></button>
			            </div>
			            
			            <div class="col-sm-5">
			            	<label style="text-align: left;margin-left: 10px;">Stock Out <span class="required-indicator">*</span></label>
			                <select name="to" id="optgroup_to" class="form-control" size="8" multiple="multiple" style="height: 450px;">
		                        <g:each in="${scb.Category.list()}">
	                        	  <optgroup label="${it.name}">
	                        	  	<g:each in="${it.productList.findAll{!it.stockAvailable}}">
			                            <option value="${it.id}">${it.name}</option>
	                        	  	</g:each>
	                        	  </optgroup>
		                        </g:each>
			                </select>
			            </div>
                	</div>
                </fieldset>
                <fieldset class="buttons">
                    <input type="button" onClick="submitData()" name="create" class="save" value="Submit" />
                    <span id="success-message"></span>
                </fieldset>
            </g:form>
        </div>
        <script type="text/javascript">
            $(document).ready(function() {
			    $('#optgroup').multiselect({multiple:true});
			});
			function submitData(){
		        var productSelected = $('#optgroup option');
		        var productUnSelected = $('#optgroup_to option');
		        var selected = [];
		        var unselected = [];
		        $(productSelected).each(function(index, brand){
		            selected.push($(this).val());
		        });
		        $(productUnSelected).each(function(index, brand){
		            unselected.push($(this).val());
		        });
                jQuery.ajax({
                    url: '/category/stockUpdate',
                    data: {
                    	in: selected,
                    	out: unselected
                    },
                    method: 'POST',
                    success: function(data){
                    	if(data.status){
	                    	$("#success-message").html("<span style='color:green;'>Updated Successfully</span>");
                    	}else{
	                    	$("#success-message").html("<span style='color:red;'>Updation Failure</span>");
                    	}
                    }
				});				
			}
	    </script>
    </body>
</html>